'use strict';

/**
 * Regenerates tests/vectors/key-import-envelope-v1.json.
 *
 *     node tests/vectors/generateKeyImportEnvelopeVectors.js
 *
 * Every input below is FIXED and checked in, so the file is reproducible byte for byte and the
 * Go side (mpc-node / mpc-node-api) can be tested against exactly these bytes without running
 * the tool. Nothing here is real key material — the two P-256 keypairs were generated for this
 * file and are used nowhere else.
 *
 * The intermediates (sharedSecret, kek, bindingDigest) are published on purpose: when the Go
 * implementation disagrees on the final payload, they say WHICH step diverged.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const envelope = require('../../src/lib/utils/keyImportEnvelope');

const OUTPUT_FILE = path.join(__dirname, 'key-import-envelope-v1.json');

// A recipient node's long-term identity key. mpc-node holds the private half as base64 of the
// SEC1 DER (config.PrivateKey -> x509.ParseECPrivateKey) and publishes the public half as base64
// of the PKIX DER (config.DerivePublicKey).
const RECIPIENT_PRIVATE_KEY_PEM = [
    '-----BEGIN EC PRIVATE KEY-----',
    'MHcCAQEEIG+90ZhpoZOZBQ3dHC5XlraqHRiiQAmRxNAiTfiUzd8roAoGCCqGSM49',
    'AwEHoUQDQgAEhzFzO91z1Jg81jEUMOKQ6gfeME5QToaM99a0fZKyqE5bwc4nK/Cg',
    'nGv1PM/dhMIgSctAUgR5w0wODFwHW2AE6Q==',
    '-----END EC PRIVATE KEY-----',
].join('\n');

// The per-part ephemeral key. In production this is freshly generated inside sealPoint and the
// private half is dropped; it is pinned here only so the vectors are deterministic.
const EPHEMERAL_PRIVATE_KEY_PEM = [
    '-----BEGIN EC PRIVATE KEY-----',
    'MHcCAQEEIMb9dscDkhUgzWccWEynrtBsFeEqo1Xe++jlEWo71nHEoAoGCCqGSM49',
    'AwEHoUQDQgAEET9fP3VV2Sur9UqTsg04SoO5p5aoCDMOpk2oWYa4uxVn2z7aXsPw',
    'f4oPD/lTPcHaBmm74s1GCFvC+8s5hLS7Fw==',
    '-----END EC PRIVATE KEY-----',
].join('\n');

const SESSION_ID_HEX = 'ebc19e1fc9a1099d3eae57ee02c59fe5';
const NONCE_HEX = '49ee048298349ef74380032e';

// The 32-byte polynomial point being sealed — the secret this whole envelope exists to protect.
const POINT_HEX = '56e7e15a0cf061ce006ca5234cad5ecd99ac899b5846850096aae92b94586b2c';

const BINDING = {
    keyId: '5d8af83c-fb02-497b-b3fd-9e2fc7351f75',
    oldKeyId: '064238f9-ec2d-4891-b1a7-f449a7c3059d',
    algorithm: 'ecdsa',
    importerIndex: 3,
    newThreshold: 3,
    oldThreshold: 2,
    // The RETIRED group public key, uncompressed SEC1 secp256k1, as mpc-node stores it.
    publicKey: '0449b9bfecedab2b7b9756e36bd8969799fd86c5254aeb0de275045d5023aceceeec73'
        + '6276df8727ddd86db4a191551941cf0f4275ad06f42b780ff7dc157a27a7',
    // The RETIRED chain code.
    chainCode: '9770664a53efd2ab3094cb2ad9fe04c3d28950374e2257bb64a903e2de767cb4',
};

/**
 * @param {crypto.KeyObject} privateKey
 * @return {{privateKeyPem: string, privateKeySec1Base64: string, publicKeyPkixBase64: string}}
 */
function describeKeyPair(privateKey) {
    const publicKey = crypto.createPublicKey(privateKey);

    return {
        privateKeyPem: privateKey.export({type: 'sec1', format: 'pem'}).toString().trim(),
        privateKeySec1Base64: privateKey.export({type: 'sec1', format: 'der'}).toString('base64'),
        publicKeyPkixBase64: publicKey.export({type: 'spki', format: 'der'}).toString('base64'),
    };
}

/**
 * @return {object}
 */
function buildVectors() {
    const recipientPrivateKey = crypto.createPrivateKey(RECIPIENT_PRIVATE_KEY_PEM);
    const ephemeralPrivateKey = crypto.createPrivateKey(EPHEMERAL_PRIVATE_KEY_PEM);
    const recipient = describeKeyPair(recipientPrivateKey);
    const ephemeral = describeKeyPair(ephemeralPrivateKey);
    const sessionId = Buffer.from(SESSION_ID_HEX, 'hex');

    const sealed = envelope.sealPoint({
        point: POINT_HEX,
        recipientPublicKey: recipient.publicKeyPkixBase64,
        sessionId: sessionId,
        binding: BINDING,
        ephemeralPrivateKey: ephemeralPrivateKey,
        nonce: NONCE_HEX,
    });

    const {sharedSecret, kek} = envelope.deriveKek(
        ephemeralPrivateKey,
        crypto.createPublicKey(recipientPrivateKey),
        sessionId
    );

    return {
        description: 'Fixed ENVELOPE v1 test vectors for the MPC key-import share sealing. '
            + 'Generated by tests/vectors/generateKeyImportEnvelopeVectors.js. No real key '
            + 'material — the keypairs exist only for this file.',
        version: envelope.ENVELOPE_LABEL,
        kekInfoLabel: envelope.KEK_INFO_LABEL,
        curve: 'prime256v1',
        kdf: 'HKDF-SHA256(ikm = ECDH shared X, salt = nil, info = kekInfoLabel || hex(sessionId), len = 32)',
        aead: 'AES-256-GCM, aad = SHA-256 of the length-prefixed canonical binding',
        wireForm: 'senderPublicKey = base64(PKIX DER of the ephemeral public key); '
            + 'payload = base64(nonce || ciphertext || tag)',
        bindingElementOrder: [
            'label ("' + envelope.ENVELOPE_LABEL + '", ASCII)',
            'keyId (ASCII uuid)',
            'oldKeyId (ASCII uuid)',
            'algorithm (ASCII)',
            'importerIndex (decimal ASCII)',
            'newThreshold (decimal ASCII)',
            'oldThreshold (decimal ASCII)',
            'publicKey (raw bytes of the retired group public key)',
            'chainCode (raw bytes of the retired chain code)',
        ],
        bindingElementPrefix: 'each element is preceded by its byte length as a 4-byte big-endian uint32',
        input: {
            recipient: recipient,
            ephemeral: ephemeral,
            sessionIdHex: SESSION_ID_HEX,
            nonceHex: NONCE_HEX,
            pointHex: POINT_HEX,
            binding: BINDING,
        },
        expected: {
            sharedSecretHex: sharedSecret.toString('hex'),
            kekHex: kek.toString('hex'),
            bindingDigestHex: sealed.bindingDigest.toString('hex'),
            ciphertextHex: sealed.ciphertext.toString('hex'),
            authTagHex: sealed.authTag.toString('hex'),
            senderPublicKey: sealed.senderPublicKey,
            payload: sealed.payload,
        },
    };
}

if (require.main === module) {
    fs.writeFileSync(OUTPUT_FILE, `${JSON.stringify(buildVectors(), null, 4)}\n`);
    process.stdout.write(`wrote ${OUTPUT_FILE}\n`);
}

module.exports = {
    OUTPUT_FILE,
    RECIPIENT_PRIVATE_KEY_PEM,
    EPHEMERAL_PRIVATE_KEY_PEM,
    SESSION_ID_HEX,
    NONCE_HEX,
    POINT_HEX,
    BINDING,
    buildVectors,
};
